### ISSUE TITLE
New Server Addresses

### ISSUE THREAD

**Issue by stew42** [mpepa/SMSGateway#1]
Please see: https://www.aspsms.com/de/xml/

"...
Neue Server-Adressen
xml1.aspsms.com und xml2.aspsms.com sind auf Servern aufgesetzt, deren Verschlüsselungsprotokolle nicht weiter aktualisiert werden.

Deshalb bitten wir Kunden, die die XML Schnittstelle nutzen, neu die Server xml3.aspsms.com und xml4.aspsms.com anzusprechen.

xml1.aspsms.com und xml2.aspsms.com stehen als Legacy-Server weiterhin zur Verfügung.
..."

**Comment by mpepa** [comment]
This is now implemented
